// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'e76e9f3c23976b38f3fd34c5571cf765b58404ab6466616cd4d93358bf196e3f'>;
export type ExecutionHash =
  ExecutionHashBase<'a499031370d1fd1891ca11072d3f7e11be752b686057f7c6d0900ee0159f4ed0'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true; };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true; };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true; };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true; };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true; };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true; };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true; };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true; };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true; };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true; };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true; };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true; };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true; };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true; };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true; };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true; };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true; };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true; };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true; };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true; };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true; };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true; };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true; };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false; };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false; };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false; };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false; };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true; };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true; };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true; };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true; };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true; };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true; };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true; };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true; };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true; };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true; };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true; };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true; };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true; };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true; };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true; };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true; };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true; };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true; };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true; };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true; };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true; };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true; };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true; };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true; };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true; };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true; };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true; };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true; };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true; };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true; };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true; };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true; };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true; };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true; };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true; };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true; };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true; };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true; };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true; };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true; };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true; };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true; };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true; };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true; };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true; };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true; };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true; };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true; };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true; };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true; };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true; };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true; };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true; };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true; };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true; };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true; };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true; };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true; };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true; };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true; };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true; };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true; };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true; };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true; };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true; };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true; };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true; };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true; };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
  ? Encoded
  : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Anime: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly malId: CodecTypes['pg/int4@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly imageUrl: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly Review: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly rating: CodecTypes['pg/int4@1']['output'];
      readonly comment: CodecTypes['pg/text@1']['output'] | null;
      readonly userId: CodecTypes['pg/int4@1']['output'];
      readonly animeId: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly User: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly username: CodecTypes['pg/text@1']['output'] | null;
      readonly name: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly UserAnime: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly status: CodecTypes['pg/text@1']['output'];
      readonly progress: CodecTypes['pg/int4@1']['output'];
      readonly userId: CodecTypes['pg/int4@1']['output'];
      readonly animeId: CodecTypes['pg/int4@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Anime: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly malId: CodecTypes['pg/int4@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly imageUrl: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly Review: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly rating: CodecTypes['pg/int4@1']['input'];
      readonly comment: CodecTypes['pg/text@1']['input'] | null;
      readonly userId: CodecTypes['pg/int4@1']['input'];
      readonly animeId: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly User: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly username: CodecTypes['pg/text@1']['input'] | null;
      readonly name: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly UserAnime: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly status: CodecTypes['pg/text@1']['input'];
      readonly progress: CodecTypes['pg/int4@1']['input'];
      readonly userId: CodecTypes['pg/int4@1']['input'];
      readonly animeId: CodecTypes['pg/int4@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly anime: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly imageUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly malId: CodecTypes['pg/int4@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
    };
    readonly review: {
      readonly animeId: CodecTypes['pg/int4@1']['output'];
      readonly comment: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly rating: CodecTypes['pg/int4@1']['output'];
      readonly userId: CodecTypes['pg/int4@1']['output'];
    };
    readonly user: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly username: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly userAnime: {
      readonly animeId: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly progress: CodecTypes['pg/int4@1']['output'];
      readonly status: CodecTypes['pg/text@1']['output'];
      readonly userId: CodecTypes['pg/int4@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly anime: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly imageUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly malId: CodecTypes['pg/int4@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
    };
    readonly review: {
      readonly animeId: CodecTypes['pg/int4@1']['input'];
      readonly comment: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly rating: CodecTypes['pg/int4@1']['input'];
      readonly userId: CodecTypes['pg/int4@1']['input'];
    };
    readonly user: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly username: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly userAnime: {
      readonly animeId: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly progress: CodecTypes['pg/int4@1']['input'];
      readonly status: CodecTypes['pg/text@1']['input'];
      readonly userId: CodecTypes['pg/int4@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly anime: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly malId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly title: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly imageUrl: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id']; };
              uniques: readonly [{ readonly columns: readonly ['malId']; }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly review: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly rating: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly comment: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly userId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly animeId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()'; };
                };
              };
              primaryKey: { readonly columns: readonly ['id']; };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'review_userId_idx_a489d58a';
                  readonly prefix: 'review_userId_idx';
                  readonly columns: readonly ['userId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'review_animeId_idx_46bb9889';
                  readonly prefix: 'review_animeId_idx';
                  readonly columns: readonly ['animeId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'review';
                    readonly columns: readonly ['userId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'review';
                    readonly columns: readonly ['animeId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'anime';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly user: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly username: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()'; };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id']; };
              uniques: readonly [{ readonly columns: readonly ['email']; }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly userAnime: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly progress: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly userId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly animeId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id']; };
              uniques: readonly [{ readonly columns: readonly ['userId', 'animeId']; }];
              indexes: readonly [
                {
                  readonly name: 'userAnime_userId_idx_a489d58a';
                  readonly prefix: 'userAnime_userId_idx';
                  readonly columns: readonly ['userId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'userAnime_animeId_idx_46bb9889';
                  readonly prefix: 'userAnime_animeId_idx';
                  readonly columns: readonly ['animeId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'userAnime';
                    readonly columns: readonly ['userId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'userAnime';
                    readonly columns: readonly ['animeId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'anime';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly user: { readonly namespace: 'public' & NamespaceId; readonly model: 'User'; };
    readonly anime: { readonly namespace: 'public' & NamespaceId; readonly model: 'Anime'; };
    readonly userAnime: { readonly namespace: 'public' & NamespaceId; readonly model: 'UserAnime'; };
    readonly review: { readonly namespace: 'public' & NamespaceId; readonly model: 'Review'; };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Anime: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1'; };
              };
              readonly malId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1'; };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1'; };
              };
              readonly imageUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1'; };
              };
            };
            readonly relations: {
              readonly reviews: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Review';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['animeId'];
                };
              };
              readonly users: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'UserAnime';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['animeId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'anime';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id'; };
                readonly malId: { readonly column: 'malId'; };
                readonly title: { readonly column: 'title'; };
                readonly imageUrl: { readonly column: 'imageUrl'; };
              };
            };
          };
          readonly Review: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1'; };
              };
              readonly rating: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1'; };
              };
              readonly comment: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1'; };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1'; };
              };
              readonly animeId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1'; };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly anime: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Anime';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['animeId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User'; };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'review';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id'; };
                readonly rating: { readonly column: 'rating'; };
                readonly comment: { readonly column: 'comment'; };
                readonly userId: { readonly column: 'userId'; };
                readonly animeId: { readonly column: 'animeId'; };
                readonly createdAt: { readonly column: 'createdAt'; };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1'; };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1'; };
              };
              readonly username: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1'; };
              };
              readonly name: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1'; };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly animeList: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'UserAnime';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
              readonly reviews: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Review';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'user';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id'; };
                readonly email: { readonly column: 'email'; };
                readonly username: { readonly column: 'username'; };
                readonly name: { readonly column: 'name'; };
                readonly createdAt: { readonly column: 'createdAt'; };
                readonly updatedAt: { readonly column: 'updatedAt'; };
              };
            };
          };
          readonly UserAnime: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1'; };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1'; };
              };
              readonly progress: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1'; };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1'; };
              };
              readonly animeId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1'; };
              };
            };
            readonly relations: {
              readonly anime: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Anime';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['animeId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User'; };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'userAnime';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id'; };
                readonly status: { readonly column: 'status'; };
                readonly progress: { readonly column: 'progress'; };
                readonly userId: { readonly column: 'userId'; };
                readonly animeId: { readonly column: 'animeId'; };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'user';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow'; };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow'; };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
